# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0008_samplereads_num_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledGenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CallingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='calledgenotype',
            name='calling_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.CallingScheme'),
        ),
        migrations.AddField(
            model_name='calledgenotype',
            name='histogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Histogram'),
        ),
        migrations.AddField(
            model_name='calledgenotype',
            name='microsatellite_genotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.MicrosatelliteHistogramGenotype'),
        ),
    ]
