# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sequencing.calling.range
import sequencing.calling.simcor.models_common
import sequencing.calling.simcor.range
import sequencing.calling.simcor.schema_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledAlleles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CallingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MicrosatelliteAlleleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele1', models.PositiveSmallIntegerField(default=0)),
                ('allele2', models.PositiveSmallIntegerField(default=0)),
                ('allele3', models.PositiveSmallIntegerField(default=0)),
                ('allele4', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(models.Model, sequencing.calling.range.MultiAlleleMixin),
        ),
        migrations.CreateModel(
            name='Proportions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('p2', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('p3', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('p4', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationsByCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sim_hists', models.FilePathField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='BestCorrelationCalledAlleles',
            fields=[
                ('calledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles')),
                ('confidence', models.FloatField()),
                ('cycle', models.PositiveSmallIntegerField()),
            ],
            bases=('calling.calledalleles',),
        ),
        migrations.CreateModel(
            name='BoundProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('lower_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('upper_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.BoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='FullBiSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.FullRangeBiMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='FullMonoSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BaseMonoAllelicMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.AllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='HighestPeak',
            fields=[
                ('calledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles')),
                ('confidence', models.FloatField()),
            ],
            bases=('calling.calledalleles',),
        ),
        migrations.CreateModel(
            name='HighestPeaksMonoSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BaseMonoAllelicMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.range.AllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='HighestPeaksProportionalBiSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('lower_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('upper_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('minimal_seeds_distance', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.range.BoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.schema_models.BestCorrelationProportionalHighestPeakCalledAlleleMIxin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='HighestPeaksProximityRatioFilteredBiSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('lower_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('upper_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('length_sensitivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('diff_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('minimal_seeds_distance', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.schema_models.BestCorrelationProportionalHighestPeakCalledAlleleMIxin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProximityRatioFilteredBoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='ProportionalMicrosatelliteAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
                ('proportions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.Proportions')),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.CreateModel(
            name='ProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='ProximityRatioFilteredBoundProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('lower_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('upper_prop_bound', models.DecimalField(decimal_places=5, max_digits=6)),
                ('length_sensitivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('diff_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProximityRatioFilteredBoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='ProximityRatioFilteredProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=5, max_digits=6)),
                ('length_sensitivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('diff_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProximityRatioFilteredProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='SingleMicrosatelliteAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.AlterUniqueTogether(
            name='microsatellitealleleset',
            unique_together=set([('allele1', 'allele2', 'allele3', 'allele4')]),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='calling_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.CallingScheme'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='genotypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.MicrosatelliteAlleleSet'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='histogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Histogram'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='microsatellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Microsatellite'),
        ),
        migrations.CreateModel(
            name='BestCorrelationProportionalCalledAlleles',
            fields=[
                ('bestcorrelationcalledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.BestCorrelationCalledAlleles')),
            ],
            bases=('calling.bestcorrelationcalledalleles',),
        ),
        migrations.CreateModel(
            name='BestCorrelationProportionalHighestPeakCalledAlleles',
            fields=[
                ('bestcorrelationcalledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.BestCorrelationCalledAlleles')),
            ],
            bases=('calling.bestcorrelationcalledalleles',),
        ),
        migrations.AlterUniqueTogether(
            name='calledalleles',
            unique_together=set([('histogram', 'microsatellite', 'calling_scheme')]),
        ),
    ]
