# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestPeak',
            fields=[
                ('calledgenotype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledGenotype')),
                ('confidence', models.FloatField()),
            ],
            bases=('calling.calledgenotype',),
        ),
    ]
