# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sequencing.calling.range
import sequencing.calling.simcor.models_common
import sequencing.calling.simcor.range
import sequencing.calling.simcor.schema_models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0002_bulk_of_calling_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestPeaksProximityRatioFilteredBiSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lower_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('upper_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('length_sensitivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('diff_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('minimal_seeds_distance', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalHighestPeakCalledAlleleMIxin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.range.ProximityRatioFilteredBoundProportionalAllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='ProximityRatioFilteredBoundProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lower_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('upper_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('length_sensitivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('diff_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProximityRatioFilteredBoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='ProximityRatioFilteredProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
                ('length_sensitivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('diff_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cycle_sensetivity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProximityRatioFilteredProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
    ]
