# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sequencing.calling.range
import sequencing.calling.simcor.models_common
import sequencing.calling.simcor.range
import sequencing.calling.simcor.schema_models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20170104_0934'),
        ('planning', '0007_add_fk'),
        ('calling', '0002_highestpeak'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lower_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('upper_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.BoundProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='CalledAlleles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FullBiSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.FullRangeBiMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='FullMonoSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.AllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='HighestPeaksBiSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lower_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('upper_prop_bound', models.DecimalField(decimal_places=2, max_digits=3)),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('minimal_seeds_distance', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalHighestPeakCalledAlleleMIxin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.range.BoundProportionalAllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.range.ProportionsBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='MicrosatelliteAlleleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele1', models.PositiveSmallIntegerField(null=True)),
                ('allele2', models.PositiveSmallIntegerField(null=True)),
                ('allele3', models.PositiveSmallIntegerField(null=True)),
                ('allele4', models.PositiveSmallIntegerField(null=True)),
            ],
            bases=(models.Model, sequencing.calling.range.MultiAlleleMixin),
        ),
        migrations.CreateModel(
            name='ProportionalSimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('proportion_step', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalCalledAlleleMixin, sequencing.calling.simcor.schema_models.BaseBiAllelicMixin, sequencing.calling.simcor.range.ProportionalAllelesCyclesRangeMixin, sequencing.calling.simcor.schema_models.ProportionalSimCorSchemeMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.CreateModel(
            name='Proportions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('p3', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('p4', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationsByCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sim_hists', models.FilePathField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='calling_scheme',
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='histogram',
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='microsatellite_genotype',
        ),
        migrations.RemoveField(
            model_name='highestpeak',
            name='calledgenotype_ptr',
        ),
        migrations.CreateModel(
            name='BestCorrelationCalledAlleles',
            fields=[
                ('calledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles')),
                ('confidence', models.FloatField()),
                ('cycle', models.PositiveSmallIntegerField()),
            ],
            bases=('calling.calledalleles',),
        ),
        migrations.CreateModel(
            name='ProportionalMicrosatelliteAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
                ('proportions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.Proportions')),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.CreateModel(
            name='SingleMicrosatelliteAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.DeleteModel(
            name='CalledGenotype',
        ),
        migrations.AddField(
            model_name='proportionalsimcorscheme',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AlterUniqueTogether(
            name='microsatellitealleleset',
            unique_together=set([('allele1', 'allele2', 'allele3', 'allele4')]),
        ),
        migrations.AddField(
            model_name='highestpeaksbisimcorschememodel',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AddField(
            model_name='fullmonosimcorscheme',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AddField(
            model_name='fullbisimcorscheme',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='calling_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.CallingScheme'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='genotypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.MicrosatelliteAlleleSet'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='histogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Histogram'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='microsatellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Microsatellite'),
        ),
        migrations.AddField(
            model_name='boundproportionalsimcorscheme',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AddField(
            model_name='highestpeak',
            name='calledalleles_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BestCorrelationProportionalCalledAlleles',
            fields=[
                ('bestcorrelationcalledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.BestCorrelationCalledAlleles')),
            ],
            bases=('calling.bestcorrelationcalledalleles',),
        ),
        migrations.CreateModel(
            name='BestCorrelationProportionalHighestPeakCalledAlleles',
            fields=[
                ('bestcorrelationcalledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.BestCorrelationCalledAlleles')),
            ],
            bases=('calling.bestcorrelationcalledalleles',),
        ),
        migrations.AlterUniqueTogether(
            name='calledalleles',
            unique_together=set([('histogram', 'microsatellite', 'calling_scheme')]),
        ),
    ]
