# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_add_fk'),
        ('analysis', '0012_auto_20170104_0934'),
        ('calling', '0002_highestpeak'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledAlleles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MicrosatelliteAlleleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele1', models.PositiveSmallIntegerField()),
                ('allele2', models.PositiveSmallIntegerField()),
                ('allele3', models.PositiveSmallIntegerField()),
                ('allele4', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimCorScheme',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('calling.callingscheme', models.Model),
        ),
        migrations.CreateModel(
            name='SimulationsByCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sim_hists', models.FilePathField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='calling_scheme',
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='histogram',
        ),
        migrations.RemoveField(
            model_name='calledgenotype',
            name='microsatellite_genotype',
        ),
        migrations.RemoveField(
            model_name='highestpeak',
            name='calledgenotype_ptr',
        ),
        migrations.AddField(
            model_name='callingscheme',
            name='max_ms_len',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callingscheme',
            name='min_ms_len',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BestCorrelationCalledAlleles',
            fields=[
                ('calledalleles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles')),
                ('confidence', models.FloatField()),
                ('cycle', models.PositiveSmallIntegerField()),
            ],
            bases=('calling.calledalleles',),
        ),
        migrations.CreateModel(
            name='NaiveBiallelicSimCorScheme',
            fields=[
                ('simcorscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.SimCorScheme')),
                ('minimal_seeds_distance', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('calling.simcorscheme',),
        ),
        migrations.CreateModel(
            name='ProportionalMSAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
                ('p1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('p3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('p4', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.CreateModel(
            name='SingleMicrosatelliteAlleleSet',
            fields=[
                ('microsatellitealleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.MicrosatelliteAlleleSet')),
            ],
            bases=('calling.microsatellitealleleset',),
        ),
        migrations.DeleteModel(
            name='CalledGenotype',
        ),
        migrations.AddField(
            model_name='simcorscheme',
            name='simulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles'),
        ),
        migrations.AlterUniqueTogether(
            name='microsatellitealleleset',
            unique_together=set([('allele1', 'allele2', 'allele3', 'allele4')]),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='calling_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.CallingScheme'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='genotypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.MicrosatelliteAlleleSet'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='histogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Histogram'),
        ),
        migrations.AddField(
            model_name='calledalleles',
            name='microsatellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Microsatellite'),
        ),
        migrations.AddField(
            model_name='highestpeak',
            name='calledalleles_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CalledAlleles'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProportionalBiAllelicMSAlleleSet',
            fields=[
                ('proportionalmsalleleset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.ProportionalMSAlleleSet')),
            ],
            bases=('calling.proportionalmsalleleset',),
        ),
        migrations.AlterUniqueTogether(
            name='calledalleles',
            unique_together=set([('histogram', 'microsatellite', 'calling_scheme')]),
        ),
    ]
