# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sequencing.calling.range
import sequencing.calling.simcor.models_common
import sequencing.calling.simcor.range
import sequencing.calling.simcor.schema_models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0004_MicrosatelliteAlleleSet_null_to_zero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestPeaksMonoSimCorSchemeModel',
            fields=[
                ('callingscheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.CallingScheme')),
                ('min_cycles', models.PositiveSmallIntegerField()),
                ('max_cycles', models.PositiveSmallIntegerField()),
                ('min_ms_len', models.PositiveSmallIntegerField()),
                ('max_ms_len', models.PositiveSmallIntegerField()),
                ('range_from_point', models.PositiveSmallIntegerField()),
                ('simulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calling.SimulationsByCycles')),
            ],
            options={
                'abstract': False,
            },
            bases=(sequencing.calling.simcor.schema_models.BestCorrelationProportionalHighestPeakCalledAlleleMIxin, sequencing.calling.simcor.schema_models.BaseMonoAllelicMixin, sequencing.calling.simcor.schema_models.BestCorrelationCalledAlleleMixin, 'calling.callingscheme', models.Model, sequencing.calling.simcor.range.HighestPeaksMixin, sequencing.calling.simcor.schema_models.FilterByHistMixin, sequencing.calling.simcor.range.AllelesCyclesRangeMixin, sequencing.calling.range.MSLengthBoundsMixin, sequencing.calling.simcor.models_common.CycleBoundsMixin),
        ),
    ]
