# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0005_highestpeaksmonosimcorschememodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundproportionalsimcorscheme',
            name='lower_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boundproportionalsimcorscheme',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boundproportionalsimcorscheme',
            name='upper_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproportionalbisimcorschememodel',
            name='lower_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproportionalbisimcorschememodel',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproportionalbisimcorschememodel',
            name='upper_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='cycle_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='diff_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='length_sensitivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='lower_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodel',
            name='upper_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proportionalsimcorscheme',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proportions',
            name='p1',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='proportions',
            name='p2',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='proportions',
            name='p3',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='proportions',
            name='p4',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='cycle_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='diff_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='length_sensitivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='lower_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredboundproportionalsimcorscheme',
            name='upper_prop_bound',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredproportionalsimcorscheme',
            name='cycle_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredproportionalsimcorscheme',
            name='diff_sensetivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredproportionalsimcorscheme',
            name='length_sensitivity',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proximityratiofilteredproportionalsimcorscheme',
            name='proportion_step',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
