# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0006_auto_20180710_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestPeaksProximityRatioFilteredBiSimCorSchemeModelDot',
            fields=[
                ('highestpeaksproximityratiofilteredbisimcorschememodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calling.HighestPeaksProximityRatioFilteredBiSimCorSchemeModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('calling.highestpeaksproximityratiofilteredbisimcorschememodel',),
        ),
    ]
