# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-20 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0009_highestpeaksproximityratiofilteredbisimcorschememodeldotba'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proportions',
            unique_together=set([('p1', 'p2', 'p3', 'p4')]),
        ),
    ]
