# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0011_highestpeaksproximityratiofilteredbisimcorschememodeldotbamms'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestpeaksproximityratiofilteredbisimcorschememodeldotba',
            name='is_prf',
            field=models.BooleanField(default=True),
        ),
    ]
