# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linapp', '0001_initial'),
    ]

    state_ops = [
        migrations.RemoveField(
            model_name='individual',
            name='taxa',
        ),
        migrations.RemoveField(
            model_name='platestorage',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='type',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='chromosome',
        ),
        migrations.RemoveField(
            model_name='extractionevent',
            name='user_documented',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='validation_failure',
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='targetenrichmenttype',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='restrictionsite',
            name='target_ptr',
        ),
        migrations.AlterIndexTogether(
            name='samplelocation',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='status',
        ),
        migrations.RemoveField(
            model_name='restrictionsite',
            name='restriction_type',
        ),
        migrations.RemoveField(
            model_name='facs',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='platetype',
            name='plastic',
        ),
        migrations.RemoveField(
            model_name='primer',
            name='tail',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='sampling',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='location',
        ),
        migrations.RemoveField(
            model_name='platestorage',
            name='storageBox',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='tissue',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='storagebox',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='primer',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='target',
            name='chromosome',
        ),
        migrations.RemoveField(
            model_name='extractionevent',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='primersmultiplex',
            name='primers',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='extractionevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='target',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='primer',
            name='target_ptr',
        ),
        migrations.RemoveField(
            model_name='facs',
            name='samplingevent_ptr',
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='target_ptr',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='samplelocation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='extractionevent',
            name='user_performed',
        ),
        migrations.RemoveField(
            model_name='lasercapture',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='cellselector',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='extraction_event',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='left',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='taxa',
        ),
        migrations.RemoveField(
            model_name='samplingevent',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='cellselector',
            name='samplingevent_ptr',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='background',
        ),
        migrations.RemoveField(
            model_name='chromosome',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='target',
            name='type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='type',
        ),
        migrations.RemoveField(
            model_name='samplingevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='target',
            name='referencevalue',
        ),
        migrations.RemoveField(
            model_name='cellcontent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='samplelocation',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='targetenrichment',
            name='right',
        ),
        migrations.RemoveField(
            model_name='lasercapture',
            name='samplingevent_ptr',
        ),
        migrations.RemoveField(
            model_name='microsatellite',
            name='target_ptr',
        ),
        migrations.RemoveField(
            model_name='platetype',
            name='context',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='cells',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='individual',
        ),
        migrations.DeleteModel(
            name='Assembly',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='CellContent',
        ),
        migrations.DeleteModel(
            name='CellContentType',
        ),
        migrations.DeleteModel(
            name='CellSelector',
        ),
        migrations.DeleteModel(
            name='Chromosome',
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.DeleteModel(
            name='Extraction',
        ),
        migrations.DeleteModel(
            name='ExtractionEvent',
        ),
        migrations.DeleteModel(
            name='FACS',
        ),
        migrations.DeleteModel(
            name='FACSMarker',
        ),
        migrations.DeleteModel(
            name='GeneticBackground',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='LaserCapture',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineType',
        ),
        migrations.DeleteModel(
            name='Microsatellite',
        ),
        migrations.DeleteModel(
            name='Organ',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='PlateContext',
        ),
        migrations.DeleteModel(
            name='PlatePlastica',
        ),
        migrations.DeleteModel(
            name='PlateStorage',
        ),
        migrations.DeleteModel(
            name='PlateType',
        ),
        migrations.DeleteModel(
            name='Primer',
        ),
        migrations.DeleteModel(
            name='PrimerTail',
        ),
        migrations.DeleteModel(
            name='PrimersMultiplex',
        ),
        migrations.DeleteModel(
            name='RestrictionSite',
        ),
        migrations.DeleteModel(
            name='RestrictionSiteType',
        ),
        migrations.DeleteModel(
            name='SNP',
        ),
        migrations.DeleteModel(
            name='SampleComposition',
        ),
        migrations.DeleteModel(
            name='SampleLocation',
        ),
        migrations.DeleteModel(
            name='SampleStatus',
        ),
        migrations.DeleteModel(
            name='SamplingEvent',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='Sequencing',
        ),
        migrations.DeleteModel(
            name='StorageBox',
        ),
        migrations.DeleteModel(
            name='StorageType',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='TargetEnrichment',
        ),
        migrations.DeleteModel(
            name='TargetEnrichmentFailureType',
        ),
        migrations.DeleteModel(
            name='TargetEnrichmentType',
        ),
        migrations.DeleteModel(
            name='TargetType',
        ),
        migrations.DeleteModel(
            name='Taxa',
        ),
        migrations.DeleteModel(
            name='Tissue',
        ),
    ]

    db_ops = [
        migrations.AlterModelTable(
            name='Assembly',
            table='genomes_assembly',
        ),
        migrations.AlterModelTable(
            name='Chromosome',
            table='genomes_chromosome',
        ),
        migrations.AlterModelTable(
            name='PrimerTail',
            table='genomes_primertail',
        ),
        migrations.AlterModelTable(
            name='RestrictionSiteType',
            table='genomes_restrictionsitetype',
        ),
        migrations.AlterModelTable(
            name='Sequence',
            table='genomes_sequence',
        ),
        migrations.AlterModelTable(
            name='Target',
            table='genomes_target',
        ),
        migrations.AlterModelTable(
            name='TargetEnrichment',
            table='genomes_targetenrichment',
        ),
        migrations.AlterModelTable(
            name='TargetEnrichmentFailureType',
            table='genomes_targetenrichmentfailuretype',
        ),
        migrations.AlterModelTable(
            name='TargetEnrichmentType',
            table='genomes_targetenrichmenttype',
        ),
        migrations.AlterModelTable(
            name='TargetType',
            table='genomes_targettype',
        ),
        migrations.AlterModelTable(
            name='Microsatellite',
            table='genomes_microsatellite',
        ),
        migrations.AlterModelTable(
            name='Primer',
            table='genomes_primer',
        ),
        migrations.AlterModelTable(
            name='RestrictionSite',
            table='genomes_restrictionsite',
        ),
        migrations.AlterModelTable(
            name='SNP',
            table='genomes_snp',
        ),
        migrations.AlterModelTable(
            name='Machine',
            table='lib_prep_machine',
        ),
        migrations.AlterModelTable(
            name='MachineType',
            table='lib_prep_machinetype',
        ),
        migrations.AlterModelTable(
            name='Panel',
            table='lib_prep_panel',
        ),
        migrations.AlterModelTable(
            name='PrimersMultiplex',
            table='lib_prep_primersmultiplex',
        ),
        migrations.AlterModelTable(
            name='Sequencing',
            table='lib_prep_sequencing',
        ),
        migrations.AlterModelTable(
            name='Taxa',
            table='misc_taxa',
        ),
        migrations.AlterModelTable(
            name='Cell',
            table='sampling_cell',
        ),
        migrations.AlterModelTable(
            name='CellContent',
            table='sampling_cellcontent',
        ),
        migrations.AlterModelTable(
            name='CellContentType',
            table='sampling_cellcontenttype',
        ),
        migrations.AlterModelTable(
            name='Coordinates',
            table='sampling_coordinates',
        ),
        migrations.AlterModelTable(
            name='Extraction',
            table='sampling_extraction',
        ),
        migrations.AlterModelTable(
            name='ExtractionEvent',
            table='sampling_extractionevent',
        ),
        migrations.AlterModelTable(
            name='FACSMarker',
            table='sampling_facsmarker',
        ),
        migrations.AlterModelTable(
            name='GeneticBackground',
            table='sampling_geneticbackground',
        ),
        migrations.AlterModelTable(
            name='Individual',
            table='sampling_individual',
        ),
        migrations.AlterModelTable(
            name='Location',
            table='sampling_location',
        ),
        migrations.AlterModelTable(
            name='Organ',
            table='sampling_organ',
        ),
        migrations.AlterModelTable(
            name='SampleComposition',
            table='sampling_samplecomposition',
        ),
        migrations.AlterModelTable(
            name='SampleStatus',
            table='sampling_samplestatus',
        ),
        migrations.AlterModelTable(
            name='SamplingEvent',
            table='sampling_samplingevent',
        ),
        migrations.AlterModelTable(
            name='Tissue',
            table='sampling_tissue',
        ),
        migrations.AlterModelTable(
            name='CellSelector',
            table='sampling_cellselector',
        ),
        migrations.AlterModelTable(
            name='FACS',
            table='sampling_facs',
        ),
        migrations.AlterModelTable(
            name='LaserCapture',
            table='sampling_lasercapture',
        ),
        migrations.AlterModelTable(
            name='Plate',
            table='wet_storage_plate',
        ),
        migrations.AlterModelTable(
            name='PlateContext',
            table='wet_storage_platecontext',
        ),
        migrations.AlterModelTable(
            name='PlatePlastica',
            table='wet_storage_plateplastica',
        ),
        migrations.AlterModelTable(
            name='PlateStorage',
            table='wet_storage_platestorage',
        ),
        migrations.AlterModelTable(
            name='PlateType',
            table='wet_storage_platetype',
        ),
        migrations.AlterModelTable(
            name='SampleLocation',
            table='wet_storage_samplelocation',
        ),
        migrations.AlterModelTable(
            name='StorageBox',
            table='wet_storage_storagebox',
        ),
        migrations.AlterModelTable(
            name='StorageType',
            table='wet_storage_storagetype',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celltreenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='type',
        ),
        migrations.RemoveField(
            model_name='targetanalysis',
            name='target',
        ),
        migrations.RemoveField(
            model_name='correctedrawdata',
            name='rawdata',
        ),
        migrations.RemoveField(
            model_name='targetvariant',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='cell1',
        ),
        migrations.RemoveField(
            model_name='gensig',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='algorithmrun',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='targetanalysis',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='algorithmrun',
            name='user',
        ),
        migrations.RemoveField(
            model_name='algorithmparameter',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='cell2',
        ),
        migrations.RemoveField(
            model_name='experimentuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='correctedrawdata',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='algorithmrunparameters',
            name='run',
        ),
        migrations.RemoveField(
            model_name='experimentfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experimentfile',
            name='context',
        ),
        migrations.RemoveField(
            model_name='algorithmrun',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='algorithmrunparameters',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='sequencedistribution',
            name='value',
        ),
        migrations.RemoveField(
            model_name='experimentlog',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='celltreenode',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='targetvariant',
            name='type',
        ),
        migrations.RemoveField(
            model_name='targetvariant',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='users',
        ),
        migrations.RemoveField(
            model_name='algorithmrun',
            name='ExtraFiles',
        ),
        migrations.RemoveField(
            model_name='experimentuser',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='targetanalysis',
            name='sequencingdata',
        ),
        migrations.RemoveField(
            model_name='gensig',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='targetanalysis',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='experimentfile',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='experimentuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='sequencedistribution',
            name='target',
        ),
        migrations.RemoveField(
            model_name='experimentlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sequencedistribution',
            name='failed',
        ),
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='AlgorithmParameter',
        ),
        migrations.DeleteModel(
            name='AlgorithmRun',
        ),
        migrations.DeleteModel(
            name='AlgorithmRunParameters',
        ),
        migrations.DeleteModel(
            name='AlgorithmType',
        ),
        migrations.DeleteModel(
            name='CellTreeNode',
        ),
        migrations.DeleteModel(
            name='CorrectedRawData',
        ),
        migrations.DeleteModel(
            name='DM',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='ExperimentFile',
        ),
        migrations.DeleteModel(
            name='ExperimentLog',
        ),
        migrations.DeleteModel(
            name='ExperimentUser',
        ),
        migrations.DeleteModel(
            name='FailedTargetValue',
        ),
        migrations.DeleteModel(
            name='FileContext',
        ),
        migrations.DeleteModel(
            name='GenSig',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
        migrations.DeleteModel(
            name='SequenceDistribution',
        ),
        migrations.DeleteModel(
            name='TargetAnalysis',
        ),
        migrations.DeleteModel(
            name='TargetVariant',
        ),
        migrations.DeleteModel(
            name='TargetVariantType',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_ops,
            database_operations=db_ops,
        ),
    ]
