#!/bin/bash
wget http://hgdownload.cse.ucsc.edu/goldenpath/hg19/bigZips/chromFa.tar.gz
tar -xvf chromFa.tar.gz
rm chromFa.tar.gz
for f in *.fa; do
    echo "Processing $f..."
    tail -vn +2 $f | tr --delete '\n' > ${f%%.*}.txt
    #TODO: do we need the fa files, or can we remove them?
done
