# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_increase_filename_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adamampliconreads',
            name='target_offset',
        ),
    ]
