# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplicons', '0002_create_ter_amplicons'),
        ('analysis', '0003_remove_adamampliconreads_target_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogram',
            name='amplicon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.Amplicon'),
        ),
        migrations.AddField(
            model_name='histogram',
            name='microsatellites_version',
            field=models.IntegerField(),
        ),
        migrations.AlterIndexTogether(
            name='histogramentryreads',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='histogramentryreads',
            name='amplicon',
        ),
        migrations.RemoveField(
            model_name='histogramentryreads',
            name='microsatellites_version',
        ),
    ]
