# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_move_fields_to_histogram'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adamampliconreads',
            unique_together=set([('margin_assignment', 'amplicon')]),
        ),
        migrations.AlterUniqueTogether(
            name='adammsvariations',
            unique_together=set([('amplicon', 'padding', 'microsatellites_version')]),
        ),
        migrations.AlterUniqueTogether(
            name='microsatellitehistogramgenotype',
            unique_together=set([('microsatellite', 'repeat_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='samplereads',
            unique_together=set([('demux', 'barcoded_content')]),
        ),
        migrations.AlterUniqueTogether(
            name='snphistogramgenotype',
            unique_together=set([('snp', 'base')]),
        ),
        migrations.AlterIndexTogether(
            name='microsatellitehistogramgenotype',
            index_together=set([('microsatellite', 'repeat_number')]),
        ),
        migrations.AlterIndexTogether(
            name='samplereads',
            index_together=set([('demux', 'barcoded_content')]),
        ),
        migrations.AlterIndexTogether(
            name='snphistogramgenotype',
            index_together=set([('snp', 'base')]),
        ),
    ]
