# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_unique_and_index_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosatelliteHistogramGenotypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsatellite_genotype1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
                ('microsatellite_genotype8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.MicrosatelliteHistogramGenotype')),
            ],
        ),
        migrations.CreateModel(
            name='SNPHistogramGenotypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp_genotype1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
                ('snp_genotype8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.SNPHistogramGenotype')),
            ],
        ),
        migrations.RemoveField(
            model_name='adammergedreads',
            name='assembled_fastq',
        ),
        migrations.RemoveField(
            model_name='adammergedreads',
            name='discarded_fastq',
        ),
        migrations.RemoveField(
            model_name='adammergedreads',
            name='unassembled_forward_fastq',
        ),
        migrations.RemoveField(
            model_name='adammergedreads',
            name='unassembled_reverse_fastq',
        ),
        migrations.AddField(
            model_name='adammergedreads',
            name='pear_dump_dir',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adammarginassignment',
            name='reads_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AdamReadsIndex', unique=True),
        ),
        migrations.AlterField(
            model_name='adammergedreads',
            name='sample_reads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.SampleReads', unique=True),
        ),
        migrations.RemoveField(
            model_name='histogramentryreads',
            name='microsatellite_genotypes',
        ),
        migrations.RemoveField(
            model_name='histogramentryreads',
            name='snp_genotypes',
        ),
        migrations.AlterUniqueTogether(
            name='adamhistogram',
            unique_together=set([('amplicon_reads', 'ms_variations')]),
        ),
        migrations.AlterUniqueTogether(
            name='adamreadsindex',
            unique_together=set([('merged_reads', 'included_reads', 'padding')]),
        ),
        migrations.AlterIndexTogether(
            name='adamhistogram',
            index_together=set([('amplicon_reads', 'ms_variations')]),
        ),
        migrations.AlterIndexTogether(
            name='adamreadsindex',
            index_together=set([('merged_reads', 'included_reads', 'padding')]),
        ),
        migrations.AddField(
            model_name='histogramentryreads',
            name='microsatellite_genotypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.MicrosatelliteHistogramGenotypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histogramentryreads',
            name='snp_genotypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analysis.SNPHistogramGenotypes'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='snphistogramgenotypes',
            unique_together=set([('snp_genotype1', 'snp_genotype2', 'snp_genotype3', 'snp_genotype4', 'snp_genotype5', 'snp_genotype6', 'snp_genotype7', 'snp_genotype8')]),
        ),
        migrations.AlterIndexTogether(
            name='snphistogramgenotypes',
            index_together=set([('snp_genotype1', 'snp_genotype2', 'snp_genotype3', 'snp_genotype4', 'snp_genotype5', 'snp_genotype6', 'snp_genotype7', 'snp_genotype8')]),
        ),
        migrations.AlterUniqueTogether(
            name='microsatellitehistogramgenotypes',
            unique_together=set([('microsatellite_genotype1', 'microsatellite_genotype2', 'microsatellite_genotype3', 'microsatellite_genotype4', 'microsatellite_genotype5', 'microsatellite_genotype6', 'microsatellite_genotype7', 'microsatellite_genotype8')]),
        ),
        migrations.AlterIndexTogether(
            name='microsatellitehistogramgenotypes',
            index_together=set([('microsatellite_genotype1', 'microsatellite_genotype2', 'microsatellite_genotype3', 'microsatellite_genotype4', 'microsatellite_genotype5', 'microsatellite_genotype6', 'microsatellite_genotype7', 'microsatellite_genotype8')]),
        ),
    ]
