# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_add_genotype_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='adamhistogram',
            name='separation_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adammarginassignment',
            name='separation_finished',
            field=models.BooleanField(default=False),
        ),
    ]
