# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplicons', '0003_ampliconcollection'),
        ('analysis', '0008_samplereads_num_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMSVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_dump_dir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200)),
                ('padding', models.PositiveIntegerField()),
                ('microsatellites_version', models.IntegerField()),
                ('amplicon_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection')),
            ],
        ),
        migrations.CreateModel(
            name='FullMSVAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorted_assignment_bam', models.FilePathField(max_length=200)),
                ('separation_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FullMSVHistogram',
            fields=[
                ('histogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.Histogram')),
                ('amplicon_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.Amplicon')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVAssignment')),
            ],
            bases=('analysis.histogram',),
        ),
        migrations.CreateModel(
            name='FullMSVMergedReads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pear_dump_dir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200)),
                ('sample_reads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.SampleReads', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fullmsvassignment',
            name='merged_reads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVMergedReads', unique=True),
        ),
        migrations.AddField(
            model_name='fullmsvassignment',
            name='ms_variations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVariations'),
        ),
        migrations.AlterUniqueTogether(
            name='fullmsvhistogram',
            unique_together=set([('amplicon_copy', 'assignment')]),
        ),
        migrations.AlterIndexTogether(
            name='fullmsvhistogram',
            index_together=set([('amplicon_copy', 'assignment')]),
        ),
        migrations.AlterUniqueTogether(
            name='fullmsvariations',
            unique_together=set([('amplicon_collection', 'padding', 'microsatellites_version')]),
        ),
        migrations.AlterIndexTogether(
            name='fullmsvariations',
            index_together=set([('amplicon_collection', 'padding', 'microsatellites_version')]),
        ),
    ]
