# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_histogram_num_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMSVAssignmentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_bam', models.FilePathField(max_length=200)),
                ('separation_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FullMSVMergedReadsPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastq_part', models.FilePathField(max_length=200)),
                ('start_row', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('merged_reads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVMergedReads')),
            ],
        ),
        migrations.AddField(
            model_name='fullmsvassignmentpart',
            name='merged_reads_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVMergedReadsPart', unique=True),
        ),
        migrations.AddField(
            model_name='fullmsvassignmentpart',
            name='ms_variations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVariations'),
        ),
        migrations.AlterUniqueTogether(
            name='fullmsvmergedreadspart',
            unique_together=set([('merged_reads', 'start_row', 'rows')]),
        ),
    ]
