# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_added_part_tables_for_split_fmsv'),
    ]

    operations = [
        migrations.RemoveField(  # This has been already removed TODO: track why it was automatically generated
            model_name='fullmsvassignmentpart',
            name='separation_finished',
        ),
        migrations.AlterUniqueTogether(
            name='histogramentryreads',
            unique_together=set([('histogram', 'microsatellite_genotypes', 'snp_genotypes')]),
        ),
    ]
