# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplicons', '0003_ampliconcollection'),
        ('analysis', '0012_auto_20170104_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliconCollectionBWAIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_file', models.FilePathField(allow_folders=True, max_length=200)),
                ('faidx_file', models.FilePathField(allow_folders=True, max_length=200)),
                ('index_dump_dir', models.FilePathField(allow_files=False, allow_folders=True, max_length=200)),
                ('amplicon_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadsAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bam_file', models.FilePathField(max_length=200)),
                ('alignment_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AmpliconCollectionBWAIndex')),
                ('sample_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.SampleReads')),
            ],
        ),
        migrations.CreateModel(
            name='VCFReads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcf_file', models.FilePathField(max_length=200)),
                ('reads_alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.ReadsAlignment', unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='readsalignment',
            unique_together=set([('sample_read', 'alignment_reference')]),
        ),
        migrations.CreateModel(
            name='SNPReads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cover', models.IntegerField()),
                ('snps_dict', models.FilePathField(max_length=200)),
                ('vcf_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.VCFReads')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='snpreads',
            unique_together=set([('vcf_read', 'min_cover')]),
        ),
    ]
