# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_add_AmpliconCollectionBWAIndex_ReadsAlignment_VCFReads_SNPReads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullmsvassignment',
            name='merged_reads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVMergedReads'),
        ),
        migrations.AlterField(
            model_name='fullmsvassignmentpart',
            name='merged_reads_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.FullMSVMergedReadsPart'),
        ),
        migrations.AlterUniqueTogether(
            name='fullmsvassignment',
            unique_together=set([('merged_reads', 'ms_variations')]),
        ),
        migrations.AlterUniqueTogether(
            name='fullmsvassignmentpart',
            unique_together=set([('merged_reads_part', 'ms_variations')]),
        ),
    ]
