# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demultiplexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DemultiplexingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rev_left_bc', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NGSKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('read_length', models.IntegerField(null=True)),
                ('reading_adaptor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1')),
                ('reading_adaptor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2')),
            ],
        ),
        migrations.CreateModel(
            name='NGSRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcl_directory', models.FilePathField(allow_files=False, allow_folders=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='runs.NGSKit')),
                ('libraries', models.ManyToManyField(to='workflows.Library')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MergedDemultiplexing',
            fields=[
                ('demultiplexing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runs.Demultiplexing')),
                ('ngs_runs', models.ManyToManyField(to='runs.NGSRun')),
            ],
            bases=('runs.demultiplexing',),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.MachineType'),
        ),
        migrations.AddField(
            model_name='demultiplexing',
            name='demux_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.DemultiplexingScheme'),
        ),
        migrations.AddField(
            model_name='demultiplexing',
            name='ngs_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.NGSRun'),
        ),
    ]
