# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_padlockamplificationminusprimer_padlockamplificationplusprimer'),
        ('workflows', '0004_auto_20160420_1501'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demultiplexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DemultiplexingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NGSKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_length', models.IntegerField(null=True)),
                ('reading_adaptor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1')),
                ('reading_adaptor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2')),
            ],
        ),
        migrations.AddField(
            model_name='ngsrun',
            name='bcl_directory',
            field=models.FilePathField(allow_files=False, allow_folders=True, null=True),
        ),
        migrations.AddField(
            model_name='ngsrun',
            name='libraries',
            field=models.ManyToManyField(to='workflows.Library'),
        ),
        migrations.AddField(
            model_name='demultiplexing',
            name='demux_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.DemultiplexingScheme'),
        ),
        migrations.AddField(
            model_name='demultiplexing',
            name='ngs_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.NGSRun'),
        ),
        migrations.AddField(
            model_name='ngsrun',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='runs.NGSKit'),
        ),
    ]
