# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_add_demux_etc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngsrun',
            name='user',
        ),
    ]
