# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_remove_ngsrun_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngsrun',
            name='bcl_directory',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=200, null=True),
        ),
    ]
