# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_machinetype_rev_left_bc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedDemultiplexing',
            fields=[
                ('demultiplexing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runs.Demultiplexing')),
                ('ngs_runs', models.ManyToManyField(to='runs.NGSRun')),
            ],
            bases=('runs.demultiplexing',),
        ),
    ]
