# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reagents', '0001_initial'),
        ('amplicons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM6Oligomix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ters', models.ManyToManyField(to='reagents.OM6PadlockTERBase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OM6Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amplicon_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection')),
                ('mixs', models.ManyToManyField(to='multiplexes.OM6Oligomix')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCR1Multiplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ters', models.ManyToManyField(to='reagents.PCR1PrimerPairTERBase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCR1Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amplicon_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection')),
                ('mpxs', models.ManyToManyField(to='multiplexes.PCR1Multiplex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
