# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplexes', '0002_pcr1multiplexcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCR1Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='panel',
            name='tes',
        ),
        migrations.RemoveField(
            model_name='pcr1multiplexcollection',
            name='mpxs',
        ),
        migrations.RemoveField(
            model_name='pcr1multiplexcollection',
            name='panel',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
    ]
