# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplexes', '0002_pcr1panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='tes',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
    ]
