# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplexes', '0003_auto_20160420_1501'),
        ('workflows', '0004_auto_20160420_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCR1MultiplexCollection',
        ),
        migrations.AddField(
            model_name='pcr1panel',
            name='mpxs',
            field=models.ManyToManyField(to='multiplexes.PCR1Multiplex'),
        ),
    ]
