# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0005_auto_20160502_2002'),
        ('multiplexes', '0004_auto_20160420_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM6Oligomix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ters', models.ManyToManyField(to='reagents.OM6PadlockTER')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OM6Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mixs', models.ManyToManyField(to='multiplexes.OM6Oligomix')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
