# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def populate_panel_amplicons(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PCR1Panel = apps.get_model("multiplexes", "PCR1Panel")
    OM6Panel = apps.get_model("multiplexes", "OM6Panel")
    AmpliconCollection = apps.get_model("amplicons", "AmpliconCollection")
    for p in PCR1Panel.objects.using(db_alias).all():
        amps = set()
        for mpx in p.mpxs.using(db_alias).all():
            for ter in mpx.ters.using(db_alias).select_subclasses():
                amps.add(ter.amplicon)
        ac = AmpliconCollection.objects.create()
        ac.amplicons = amps
        p.amplicon_collection = ac
        p.save()
    for p in OM6Panel.objects.using(db_alias).all():
        amps = set()
        for mix in p.mixs.using(db_alias).all():
            for ter in mix.ters.using(db_alias).select_subclasses():
                amps.add(ter.amplicon)
        ac = AmpliconCollection.objects.create()
        ac.amplicons = amps
        p.amplicon_collection = ac
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('amplicons', '0003_ampliconcollection'),
        ('multiplexes', '0004_om6oligomix_om6panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='om6panel',
            name='amplicon_collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcr1panel',
            name='amplicon_collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amplicons.AmpliconCollection'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_panel_amplicons,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
