# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import primers.strand


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genomes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionEnzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_sequence', models.CharField(max_length=50)),
                ('cut_delta', models.IntegerField()),
                ('sticky_bases', models.IntegerField()),
                ('sequence_len', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='planning.RestrictionEnzyme')),
                ('slice', models.ForeignKey(db_column='slice_id', on_delete=django.db.models.deletion.CASCADE, to='genomes.RestrictionSiteDNASlice')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TargetEnrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_version', models.IntegerField()),
                ('chromosome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genomes.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='UGSMinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genomes.DNASlice', unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, primers.strand.MinusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='UGSPlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genomes.DNASlice', unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, primers.strand.PlusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='Microsatellite',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planning.Target')),
                ('repeat_unit_len', models.PositiveIntegerField()),
                ('repeat_unit_type', models.CharField(max_length=50)),
                ('repeat_number', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('repeat_unit_ref_seq', models.CharField(max_length=50)),
                ('planning_version', models.IntegerField()),
            ],
            bases=('planning.target',),
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planning.Target')),
                ('mutation', models.CharField(max_length=10, null=True)),
                ('modified', models.CharField(max_length=10, null=True)),
            ],
            bases=('planning.target',),
        ),
        migrations.AddField(
            model_name='targetenrichment',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus'),
        ),
        migrations.AddField(
            model_name='targetenrichment',
            name='partner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetenrichment',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus'),
        ),
        migrations.AddField(
            model_name='target',
            name='partner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='target',
            name='slice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genomes.DNASlice'),
        ),
    ]
