# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_ugs_slice_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionsite',
            name='slice',
            field=models.IntegerField(db_column='slice_id'),
        ),
    ]
