# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_drop_fk'),
        ('genomes', '0007_populate_restrictionsitednaslice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionsite',
            name='slice',
            field=models.ForeignKey(db_column='slice_id', on_delete=django.db.models.deletion.CASCADE, to='genomes.RestrictionSiteDNASlice'),
        ),
    ]
