# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplicons', '0002_create_ter_amplicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliconCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplicons', models.ManyToManyField(to='amplicons.Amplicon')),
            ],
        ),
    ]
