# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_add_padlock_parts'),
        ('synthesis', '0003_om6padlock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IlluminaReadingAdaptor1Cuts',
        ),
        migrations.DeleteModel(
            name='IlluminaReadingAdaptor2Cuts',
        ),
    ]
