# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import targeted_enrichment.reagents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sampling', '0001_initial'),
        ('multiplexes', '0001_initial'),
        ('synthesis', '0001_initial'),
        ('parts', '0001_initial'),
        ('linapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmplifiedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.DNABarcode1')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.DNABarcode2')),
            ],
        ),
        migrations.CreateModel(
            name='CellContentProtocol',
            fields=[
                ('protocol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='linapp.Protocol')),
            ],
            bases=('linapp.protocol',),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PCR2PrimerPairReagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.BarcodePair')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR2PlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR2MinusPrimer')),
            ],
            bases=(targeted_enrichment.reagents.models.TwoPrimersStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MagicalOM6BarcodedContent',
            fields=[
                ('barcodedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.BarcodedContent')),
            ],
            bases=('workflows.barcodedcontent',),
        ),
        migrations.CreateModel(
            name='MagicalOM6Library',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Library')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplexes.OM6Panel')),
            ],
            bases=('workflows.library',),
        ),
        migrations.CreateModel(
            name='MagicalPCR1BarcodedContent',
            fields=[
                ('barcodedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.BarcodedContent')),
            ],
            bases=('workflows.barcodedcontent',),
        ),
        migrations.CreateModel(
            name='MagicalPCR1Library',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Library')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplexes.PCR1Panel')),
            ],
            bases=('workflows.library',),
        ),
        migrations.CreateModel(
            name='UnsupportedBarcodedContent',
            fields=[
                ('barcodedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.BarcodedContent')),
            ],
            bases=('workflows.barcodedcontent',),
        ),
        migrations.CreateModel(
            name='UnsupportedLibrary',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Library')),
            ],
            bases=('workflows.library',),
        ),
        migrations.AddField(
            model_name='barcodedcontent',
            name='barcodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.BarcodePair'),
        ),
        migrations.AddField(
            model_name='amplifiedcontent',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.CellContentProtocol'),
        ),
        migrations.AddField(
            model_name='unsupportedbarcodedcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.AmplifiedContent'),
        ),
        migrations.AddField(
            model_name='unsupportedbarcodedcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.UnsupportedLibrary'),
        ),
        migrations.AddField(
            model_name='magicalpcr1barcodedcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.AmplifiedContent'),
        ),
        migrations.AddField(
            model_name='magicalpcr1barcodedcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.MagicalPCR1Library'),
        ),
        migrations.AddField(
            model_name='magicalom6barcodedcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.AmplifiedContent'),
        ),
        migrations.AddField(
            model_name='magicalom6barcodedcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.MagicalOM6Library'),
        ),
    ]
