# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplexes', '0003_auto_20160420_1501'),
        ('workflows', '0003_auto_20160215_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicalpcr1library',
            name='mpx_collection',
        ),
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magicalpcr1library',
            name='panel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiplexes.PCR1Panel'),
            preserve_default=False,
        ),
    ]
