# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplexes', '0004_om6oligomix_om6panel'),
        ('workflows', '0004_pcr2primerpairreagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicalOM6BarcodedContent',
            fields=[
                ('barcodedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.BarcodedContent')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.AmplifiedContent')),
            ],
            bases=('workflows.barcodedcontent',),
        ),
        migrations.CreateModel(
            name='MagicalOM6Library',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Library')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplexes.OM6Panel')),
            ],
            bases=('workflows.library',),
        ),
        migrations.AddField(
            model_name='magicalom6barcodedcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.MagicalOM6Library'),
        ),
    ]
