# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0003_om6padlock'),
        ('workflows', '0004_auto_20160420_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCR2PrimerPairReagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.BarcodePair')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR2PlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR2MinusPrimer')),
            ],
        ),
    ]
