# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_add_om6_lib_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsupportedBarcodedContent',
            fields=[
                ('barcodedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.BarcodedContent')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.AmplifiedContent')),
            ],
            bases=('workflows.barcodedcontent',),
        ),
        migrations.CreateModel(
            name='UnsupportedLibrary',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Library')),
            ],
            bases=('workflows.library',),
        ),
        migrations.AddField(
            model_name='unsupportedbarcodedcontent',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.UnsupportedLibrary'),
        ),
    ]
