VARS_ADJ_MS_1 = {
    (
        "3:4=3",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=4",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=5",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=6",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=7",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=8",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=9",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=10",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=11",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=12",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=13",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=14",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=15",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=16",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=17",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=18",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=19",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=20",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=21",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=22",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=23",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=24",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=25",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=26",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=27",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=28",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=29",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=30",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=31",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=32",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=33",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=34",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=35",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=36",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=37",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=38",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=39",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=40",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=41",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=42",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=43",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=44",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=45",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=46",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=47",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=48",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=49",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=50",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=51",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=52",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=53",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=54",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=55",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=56",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ), (
        "3:4=57",
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGACCTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGTGACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ),
}
