from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

def get_fastq_record_pair(read_id, sr1, sr2):
    seq_r1 = Seq(sr1)
    seq_r2 = Seq(sr2)
    rec_r1 = SeqRecord(seq_r1, id=read_id)
    rec_r1.letter_annotations["phred_quality"] = [40] * len(seq_r1)
    rec_r2 = SeqRecord(seq_r2, id=read_id)
    rec_r2.letter_annotations["phred_quality"] = [40] * len(seq_r2)
    return rec_r1, rec_r2


read_id = "M00393:167:000000000-ABF3N:1:1101:20583:16769"
sr1 = "AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC"
sr2 = "GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAAGGGGGAGAAGCCTTTAGATCGGAAGAGCGTCGTGGGGGGAAAGGGTGGAGGGGATGGGGTAGATATCGGGGGGCGG"


