# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sampling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_group_labeling', models.CharField(max_length=50)),
                ('is_root_approximating', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FACSMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneticBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('born', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('sacrificed', models.DateTimeField(blank=True, null=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.GeneticBackground')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sample status',
                'verbose_name_plural': 'Samples status',
            },
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=sampling.models.sampling_event_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CellSelector',
            fields=[
                ('samplingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sampling.SamplingEvent')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.Coordinates')),
            ],
            bases=('sampling.samplingevent',),
        ),
        migrations.CreateModel(
            name='FACS',
            fields=[
                ('samplingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sampling.SamplingEvent')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.FACSMarker')),
            ],
            bases=('sampling.samplingevent',),
        ),
        migrations.CreateModel(
            name='LaserCapture',
            fields=[
                ('samplingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sampling.SamplingEvent')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.Coordinates')),
            ],
            bases=('sampling.samplingevent',),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Extraction'),
        ),
        migrations.AddField(
            model_name='samplingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.Location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='taxa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Taxa'),
        ),
        migrations.AddField(
            model_name='extractionevent',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Individual'),
        ),
        migrations.AddField(
            model_name='extractionevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.Location'),
        ),
        migrations.AddField(
            model_name='extractionevent',
            name='user_documented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractionevent',
            name='user_performed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraction',
            name='extraction_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.ExtractionEvent'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Organ'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='tissue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Tissue'),
        ),
        migrations.AddField(
            model_name='cell',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.SampleComposition'),
        ),
        migrations.AddField(
            model_name='cell',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Individual'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sampling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.SamplingEvent'),
        ),
        migrations.AddField(
            model_name='cell',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.SampleStatus'),
        ),
    ]
