# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='custom_group_labeling',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='is_root_approximating',
            field=models.BooleanField(default=False),
        ),
    ]
