# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('taxonomy_id', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('friendly_name', models.CharField(max_length=50)),
            ],
        ),
    ]
