# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import primers.strand
import primers.synthesis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM6Padlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umi_length', models.PositiveSmallIntegerField()),
                ('ira1ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail')),
                ('ira2ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail')),
                ('left_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
                ('right_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OM6PadlockDeprecated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umi_length', models.PositiveSmallIntegerField()),
                ('ira1ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail')),
                ('ira2ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail')),
                ('left_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
                ('right_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OM6Prep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.OM6Padlock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OM6PrepDeprecated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.OM6PadlockDeprecated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PadlockPrepCommonPrimers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('left_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart1')),
                ('left_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart2')),
                ('restriction_enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.RestrictionEnzyme')),
                ('right_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart1')),
                ('right_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart2')),
            ],
        ),
        migrations.CreateModel(
            name='PCR1MinusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail')),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR1TailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.MinusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='PCR1PlusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail')),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR1TailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.PlusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='PCR1WithCompanyTagMinusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=1)),
                ('iraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail')),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR1WithCompanyTagTailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.MinusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='PCR1WithCompanyTagPlusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=1)),
                ('iraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail')),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR1WithCompanyTagTailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.PlusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='PCR2MinusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.DNABarcode2')),
                ('ifca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaFlowCellAdaptor2')),
                ('irafh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForHead')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR2Mixin, models.Model, primers.strand.MinusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='PCR2PlusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.DNABarcode1')),
                ('ifca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaFlowCellAdaptor1')),
                ('irafh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForHead')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.PCR2Mixin, models.Model, primers.strand.PlusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='TargetedNoTailMinusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.NoTailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.MinusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.CreateModel(
            name='TargetedNoTailPlusPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
            ],
            options={
                'abstract': False,
            },
            bases=(primers.synthesis.models.NoTailMixin, primers.synthesis.models.TargetedHeadMixin, models.Model, primers.strand.PlusStrandMixin, primers.strand.BaseStrandMixin),
        ),
        migrations.AddField(
            model_name='om6prepdeprecated',
            name='primers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PadlockPrepCommonPrimers'),
        ),
        migrations.AddField(
            model_name='om6prep',
            name='primers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PadlockPrepCommonPrimers'),
        ),
        migrations.AlterUniqueTogether(
            name='padlockprepcommonprimers',
            unique_together=set([('left_amp_primer_part1', 'left_amp_primer_part2', 'right_amp_primer_part1', 'right_amp_primer_part2', 'restriction_enzyme')]),
        ),
    ]
