# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models
#import django.db.models.deletion
import django


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_add_padlock_parts'),
        ('planning', '0003_auto_20160215_1652'),
        ('synthesis', '0002_remove_temp_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM6Padlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umi_length', models.PositiveSmallIntegerField()),
                ('backbone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Backbone')),
                ('ira1ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail')),
                ('ira2ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail')),
                ('left_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSPlus')),
                ('right_ugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.UGSMinus')),
            ],
        ),
        migrations.CreateModel(
            name='OM6Prep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('left_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart1')),
                ('left_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart2')),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.OM6Padlock')),
                ('restriction_enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.RestrictionEnzyme')),
                ('right_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart1')),
                ('right_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pcr1withcompanytagminusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail'),
        ),
        migrations.RenameField(
            model_name='pcr1withcompanytagminusprimer',
            old_name='irac',
            new_name='iraft',
        ),
        migrations.AlterField(
            model_name='pcr1withcompanytagplusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail'),
        ),
        migrations.RenameField(
            model_name='pcr1withcompanytagplusprimer',
            old_name='irac',
            new_name='iraft',
        ),
        migrations.AlterField(
            model_name='pcr1minusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForTail'),
        ),
        migrations.RenameField(
            model_name='pcr1minusprimer',
            old_name='irac',
            new_name='iraft',
        ),
        migrations.AlterField(
            model_name='pcr1plusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForTail'),
        ),
        migrations.RenameField(
            model_name='pcr1plusprimer',
            old_name='irac',
            new_name='iraft',
        ),
        migrations.AlterField(
            model_name='pcr2minusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor2ForHead'),
        ),
        migrations.RenameField(
            model_name='pcr2minusprimer',
            old_name='irac',
            new_name='irafh',
        ),
        migrations.AlterField(
            model_name='pcr2plusprimer',
            name='irac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.IlluminaReadingAdaptor1ForHead'),
        ),
        migrations.RenameField(
            model_name='pcr2plusprimer',
            old_name='irac',
            new_name='irafh',
        ),
    ]
