# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_kill_cuts'),
        ('planning', '0005_ugs_slice_unique'),
        ('synthesis', '0003_om6padlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadlockPrepCommonPrimers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('left_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart1')),
                ('left_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart2')),
                ('restriction_enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.RestrictionEnzyme')),
                ('right_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart1')),
                ('right_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart2')),
            ],
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='left_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='left_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='restriction_enzyme',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='right_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='right_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='left_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='left_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='restriction_enzyme',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='right_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='right_amp_primer_part2',
        ),
        migrations.AddField(
            model_name='om6prep',
            name='primers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synthesis.PadlockPrepCommonPrimers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='om6prepdeprecated',
            name='primers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synthesis.PadlockPrepCommonPrimers'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='padlockprepcommonprimers',
            unique_together=set([('left_amp_primer_part1', 'left_amp_primer_part2', 'right_amp_primer_part1', 'right_amp_primer_part2', 'restriction_enzyme')]),
        ),
    ]
