# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from frogress import bar


def populate_padlock_primers(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PadlockPrepCommonPrimers = apps.get_model("synthesis", "PadlockPrepCommonPrimers")
    OM6Prep = apps.get_model("synthesis", "OM6Prep")
    OM6PrepDeprecated = apps.get_model("synthesis", "OM6PrepDeprecated")
    for OM in [OM6Prep, OM6PrepDeprecated]:
        print()
        for om in bar(OM.objects.using(db_alias).all()):
            primers, c = PadlockPrepCommonPrimers.objects.using(db_alias).get_or_create(
                left_amp_primer_part1=om.left_amp_primer_part1,
                left_amp_primer_part2=om.left_amp_primer_part2,
                restriction_enzyme=om.restriction_enzyme,
                right_amp_primer_part1=om.right_amp_primer_part1,
                right_amp_primer_part2=om.right_amp_primer_part2,
                defaults=dict(
                    name=om.pk,
                )
            )
            om.primers = primers
            om.save(using=db_alias)


def unpopulate_padlock_primers(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OM6Prep = apps.get_model("synthesis", "OM6Prep")
    OM6PrepDeprecated = apps.get_model("synthesis", "OM6PrepDeprecated")
    for OM in [OM6Prep, OM6PrepDeprecated]:
        print()
        for om in bar(OM.objects.using(db_alias).all()):
            primers = om.primers
            om.left_amp_primer_part1 = primers.left_amp_primer_part1
            om.left_amp_primer_part2 = primers.left_amp_primer_part2
            om.right_amp_primer_part1 = primers.right_amp_primer_part1
            om.right_amp_primer_part2 = primers.right_amp_primer_part2
            om.restriction_enzyme = primers.restriction_enzyme
            om.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_kill_cuts'),
        ('planning', '0005_ugs_slice_unique'),
        ('synthesis', '0003_om6padlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadlockPrepCommonPrimers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('left_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart1')),
                ('left_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationPlusPrimerPart2')),
                ('restriction_enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.RestrictionEnzyme')),
                ('right_amp_primer_part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart1')),
                ('right_amp_primer_part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PadlockAmplificationMinusPrimerPart2')),
            ],
        ),
        migrations.AddField(
            model_name='om6prep',
            name='primers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='synthesis.PadlockPrepCommonPrimers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='om6prepdeprecated',
            name='primers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='synthesis.PadlockPrepCommonPrimers'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='padlockprepcommonprimers',
            unique_together=set([('left_amp_primer_part1', 'left_amp_primer_part2', 'right_amp_primer_part1',
                                  'right_amp_primer_part2', 'restriction_enzyme')]),
        ),

        migrations.RunPython(
            code=populate_padlock_primers,
            reverse_code=unpopulate_padlock_primers,
        ),

        migrations.RemoveField(
            model_name='om6prep',
            name='left_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='left_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='restriction_enzyme',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='right_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prep',
            name='right_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='left_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='left_amp_primer_part2',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='restriction_enzyme',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='right_amp_primer_part1',
        ),
        migrations.RemoveField(
            model_name='om6prepdeprecated',
            name='right_amp_primer_part2',
        ),
    ]
