
from tests.sequencing.analysis.reads_dict_tools import \
    get_fastq_record_triplet, ReadIdGen


ID = ReadIdGen()


ASSEMBLED = "ASSEMBLED"
UNASSEMBLED = "UNASSEMBLED"


def bc1(sr1, sr2, srm=None):
    return get_fastq_record_triplet(
        read_id=str(ID),
        sr1=sr1,
        sr2=sr2,
        srm=srm,
        barcode1="TCCGCGAA",
        barcode2="GTACTGAC",
    )


def bc2(sr1, sr2, srm=None):
    return get_fastq_record_triplet(
        read_id=str(ID),
        sr1=sr1,
        sr2=sr2,
        srm=srm,
        barcode1="TGGGAGCC",
        barcode2="ATAGAGGC",
    )

ms_28727_a_id = 1
ms_28727_b_id = 2
ms_28734_a_id = 3
ms_adj_ms_1_a = 4
ms_adj_ms_2_a = 5
ms_adj_ms_2_b = 6
magicalpcr1library_id = 1
magicalpcr1barcodedcontent_id = 1
magicalpcr1barcodedcontent_a_id = 2
amplicon_28727_id = 1
amplicon_28734_id = 2
pu_adj_ms_1 = 3
pu_adj_ms_2 = 4
ms_unknown_id = None
amplicon_unknown_id = None


def repeat_number(i):  # Just to give the int some context
    return i

READS_DICT_FULL_MSV = {
    magicalpcr1library_id: {
        magicalpcr1barcodedcontent_id: {
            ASSEMBLED: {
                amplicon_28727_id: {
                    frozenset(((ms_28727_a_id, repeat_number(21)), (ms_28727_b_id, repeat_number(12)),)): [
                        bc1(
                            sr1="ATTTACTATGCCATGCTGCTGCTGCTTCTCTTCTTTCTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGTCTGGCATGTGCAAACAAGAACAGATGCC",
                            sr2="GGCATCTGTTCTTGTTTGCACATGCCAGACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAGGAAGAAGAGAAGCAGCAGCAGCATGGCATAGTAAAT",
                            srm="ATTTACTATGCCATGCTGCTGCTGCTTCTCTTCTTTCTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGTCTGGCATGTGCAAACAAGAACAGATGCC",
                        ),
                    ]
                },
                amplicon_28734_id: {
                    frozenset(((ms_28734_a_id, repeat_number(7)),)): [
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAAGGGGGAGAAGCCTTTAGATCGGAAGAGCGTCGTGGGGGGAAAGGGTGGAGGGGATGGGGTAGATATCGGGGGGCGG",
                            srm="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                        ),
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAATGGGGAGAAGCCTTT",
                            srm="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                        ),
                    ],
                    frozenset(((ms_28734_a_id, repeat_number(6)),)): [
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAAGGGGGAGAAGCCTTTAGATCGGAAGAGCGTCGTGGGGGGAAAGGGTGGAGGGGATGGGGTAGATATCGGGGGGCGG",
                            srm="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                        ),
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAATGGGGAGAAGCCTTT",
                            srm="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                        ),
                    ],
                },
            },
            UNASSEMBLED: {
                amplicon_28734_id: {
                    frozenset(((ms_28734_a_id, repeat_number(7)),)): [
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                        ),
                    ],
                    frozenset(((ms_28734_a_id, repeat_number(5)),)): [
                        bc1(
                            sr1="AAAGGCTTCTCCCCACTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="AAAAAAAAAAAAAAAAAAAAAAAAGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                        ),
                    ],
                },
            },
        },
        magicalpcr1barcodedcontent_a_id: {
            ASSEMBLED: {
                amplicon_28727_id: {
                    frozenset(((ms_28727_a_id, repeat_number(28)), (ms_28727_b_id, repeat_number(18)),)): [
                        bc1(
                            sr1="ATTTACTATGCCATGCTGCTGCTGCTTCTCTTCTTTCTCTTCTTCCTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTTGCTGGCATGTGCAAACAACAACAGATGCCAGAGAGGAAGAGC",
                            sr2="GGCATCTGTTCTTGTTTGCACATGCCAGACAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAAGAGGAAGAGAAGAAAGAGAAGAAGCAGCAGCAGAAAGGAAAAAAAAGAAGAGGAGAGGAGCGG",
                            srm="ATTTACTATGCCATGCTGCTGCTGCTTCTCTTCTTTCTCTTCTTCCTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTTGCTGGCATGTGCAAACAACAACAGATGCC"
                            #srm="ATTTACTATGCCATGCTGCTGCTGCTTCTCTTCTTTCTCTTCTTCCTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGTCTGGCATGTGCAAACAAGAACAGATGCC",
                        ),
                    ]
                },
                amplicon_28734_id: {
                    frozenset(((ms_28734_a_id, repeat_number(7)),)): [
                        bc1(
                            sr1="AAAGGCTTCTCCCCATTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                            sr2="GGAAGTAGTGTGTGCTTGGACTTTTCTTCTTCTTCTTCTTCTTCTCTGAGGGGAGAGGGTAGAGCAGCTGAGAGAGAGCGAGAGCGCTTCGGAACACACAGGAGATGTCGCGCGTGCTTCCTCTAAGAGATTTTCTCTTTGGAATGGGGAGAAGCCTTT",
                            srm="AAAGGCTTCTCCCCATTCCAAAGAGAAAATCTCTTAGAGGAAGCACGCGCGACATCTCCTGTGTGTTCCGAAGCGCTCTCGCTCTCTCTCAGCTGCTCTACCCTCTCCCCTCAGAGAAGAAGAAGAAGAAGAAGAAAAGTCCAAGCACACACTACTTCC",
                        ),
                    ],
                },

                pu_adj_ms_1: {
                    frozenset(((ms_adj_ms_1_a, repeat_number(30)),)): [
                        bc1(
                            sr1="AGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGAACTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGATACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCC",
                            sr2="GGCTCTATTCTTTCTCACAGGGCTAGAAAGCCACAAGTCACACTAGTGGCCAGCTGTATCTATGACCCAAACTTGCTCAGGTCTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTATGCGTGAGAGTGAGTGAGGACT",
                            srm="AGTCCTCACTGATTCTCAGGCATACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACAGAACTGAGCAAGTTTGGGTCATAGATACAGCTGGCCACTAGTGATACTTGTGGCTTTCTAGCCCTGTGAGAAAGAATAGAGCC"
                        ),
                    ]
                },
                pu_adj_ms_2: {
                    frozenset(((ms_adj_ms_2_a, repeat_number(14)), (ms_adj_ms_2_b, repeat_number(9)),)): [
                        bc1(
                            sr1="CCCTCCTTGTCCCGGCTGAGCGCACCCACCCCCGGCCTCGGCCGGGGCGAATTCGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCGCGCGCGCGCGCGCGCTCGAGTGCCGGGAGGGCAGTTGCGAAACGGGCTCTTGGCTGCAGCGCGGCATAATGGAGGTGGCTGGAAC",
                            sr2="GTTCCAGCCACCTCCATTATGCCGCGCTGCAGCCAAGAGCCCGTTTCGCAACTGCCCTCCCGGCACTCGAGCGCGCGCGCGCGCGCGCACACACACACACACACACACACACACACCAATTCGCCCCGGGCGAGGCCGGGGGTGGGTGCGCTCAGCCGGGCCCAGGCGGG",
                            srm="CCCTCCTTGTCCCGGCTGAGCGCACCCACCCCCGGCCTCGGCCGGGGCGAATTCGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCGCGCGCGCGCGCGCGCTCGAGTGCCGGGAGGGCAGTTGCGAAACGGGCTCTTGGCTGCAGCGCGGCATAATGGAGGTGGCTGGAAC"
                        ),
                    ]
                },
            },
        },
    },
}

UNKNOWN_READS_DICT_FULL_MSV = {
    magicalpcr1library_id: {
        magicalpcr1barcodedcontent_id: {
            ASSEMBLED: 
                    [
                        bc1(
                            sr1="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                            sr2="TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
                            srm="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                        ),
                    ]
        },
    },
}
