# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0003_dnaslice_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNASlice_Contains',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner', models.ForeignKey(to='genomes.DNASlice', on_delete=models.DO_NOTHING, related_name='+')),
                ('outer', models.ForeignKey(to='genomes.DNASlice', on_delete=models.DO_NOTHING, related_name='+')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RunSQL(
            sql="""
CREATE VIEW genomes_dnaslice_contains AS 
    SELECT
        s1.id AS 'inner_id',
        s2.id AS 'outer_id'
    FROM
        genomes_dnaslice s1,
        genomes_dnaslice s2
    WHERE
        s1.chromosome_id = s2.chromosome_id AND
        s1.start_pos >= s2.start_pos AND
        s1.end_pos <= s2.end_pos and s1.id <> s2.id
;
""",
            reverse_sql="DROP VIEW genomes_dnaslice_contains;"
        ),
        migrations.AddField(
            model_name='dnaslice',
            name='contains',
            field=models.ManyToManyField(related_name='contained', through='genomes.DNASlice_Contains', to='genomes.DNASlice', through_fields=('outer', 'inner')),
        ),
    ]
