# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0004_add_dnaslice_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnaslice',
            options={'ordering': ['chromosome', 'start_pos', 'end_pos']},
        ),
    ]
