# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

create_procedure = """
CREATE PROCEDURE `copy_dnaslice_restriction_data`()
BEGIN
    DECLARE max_id int  default 0;
    DECLARE max_original_id int default 0;
    SELECT MIN(gs.id) - 1, MAX(gs.id)
INTO max_id , max_original_id FROM
    genomes_dnaslice gs
        JOIN
    planning_restrictionsite pr ON (gs.id = pr.slice_id);
    while (max_id < max_original_id) do
            begin
            declare new_max,amount int default 0;
               insert into genomes_restrictionsitednaslice
             (select * from genomes_dnaslice gd where id between max_id +1 and max_id +100000);
             commit;
             set new_max = max_id +100000;
             set max_id = new_max;
            end;
    end while;
END
"""

class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0006_add_restrictionsitednaslice'),
    ]

    operations = [
        migrations.RunSQL(
            sql=create_procedure,
            reverse_sql="""
DROP PROCEDURE `copy_dnaslice_restriction_data`;
            """,
        ),

        migrations.RunSQL(
            sql="""
CALL copy_dnaslice_restriction_data();
            """,
            reverse_sql="""
TRUNCATE TABLE genomes_restrictionsitednaslice;
            """
        ),

        migrations.RunSQL(
            sql="""
    DROP PROCEDURE `copy_dnaslice_restriction_data`;
            """,
            reverse_sql=create_procedure,
        ),
    ]
