# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


delete_restrictionsites_dnaslices = """
CREATE PROCEDURE `delete_restrictionsites_dnaslices`()
BEGIN
    DECLARE max_id int  default 0;
    DECLARE max_original_id int default 0;
    SELECT MIN(gs.id) - 1, MAX(gs.id)
INTO max_id , max_original_id FROM
    genomes_dnaslice gs
        JOIN
    planning_restrictionsite pr ON (gs.id = pr.slice_id);
    while (max_id < max_original_id) do
            begin
            declare new_max,amount int default 0;
             delete from genomes_dnaslice where id between max_id +1 and max_id +100000;
             commit;
             set new_max = max_id +100000;
             set max_id = new_max;
            end;
    end while;
END
"""

populate_restrictionsites_dnaslices = """
CREATE PROCEDURE `populate_restrictionsites_dnaslices`()
    BEGIN
    	DECLARE max_id int  default 420751;
        DECLARE max_original_id int default 19466773;
    	select min(id) - 1 into max_id from genomes_dnaslice where id in (select slice_id from planning_restrictionsite);
        while (max_id < max_original_id) do
    			begin
                declare new_max,amount int default 0;
    			    insert into genomes_dnaslice
			      (select * from genomes_restrictionsitednaslice gd where id between max_id +1 and max_id +100000);
                 commit;
                 set new_max = max_id +100000;
                 set max_id = new_max;
    			end;
    	end while;
    END
        """

class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0007_populate_restrictionsitednaslice'),
        ('planning', '0006_drop_fk'),
    ]
    operations = [
        migrations.RunSQL(
            sql=delete_restrictionsites_dnaslices,
            reverse_sql="""
DROP PROCEDURE `delete_restrictionsites_dnaslices`;
            """,
        ),
        migrations.RunSQL(
            sql=populate_restrictionsites_dnaslices,
            reverse_sql="""
    DROP PROCEDURE `populate_restrictionsites_dnaslices`;
                """,
        ),
        migrations.RunSQL(
            sql="""
CALL delete_restrictionsites_dnaslices();
            """,
            reverse_sql="""
CALL populate_restrictionsites_dnaslices();
            """
        ),

        migrations.RunSQL(
            sql="""
    DROP PROCEDURE `delete_restrictionsites_dnaslices`;
            """,
            reverse_sql=delete_restrictionsites_dnaslices,
        ),
        migrations.RunSQL(
            sql="""
        DROP PROCEDURE `populate_restrictionsites_dnaslices`;
                """,
            reverse_sql=populate_restrictionsites_dnaslices,
        ),
    ]
