# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-31 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0010_add_trigger_on_dnaslice_to_populate_new_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DupSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=1)),
                ('uid', models.IntegerField()),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genomes.DNASlice')),
            ],
            options={
                'ordering': ['uid', 'slice'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dupslice',
            unique_together=set([('uid', 'slice')]),
        ),
    ]
