
from tests.sequencing.analysis.reads_dict_tools import \
    get_fastq_record_triplet, ReadIdGen

ID = ReadIdGen()


def bc1(sr1, sr2, srm=None):
    return get_fastq_record_triplet(
        read_id=str(ID),
        sr1=sr1,
        sr2=sr2,
        srm=srm,
        barcode1="TCCGCGAA",
        barcode2="GTACTGAC",
    )


def bc2(sr1, sr2, srm=None):
    return get_fastq_record_triplet(
        read_id=str(ID),
        sr1=sr1,
        sr2=sr2,
        srm=srm,
        barcode1="TGGGAGCC",
        barcode2="ATAGAGGC",
    )


def bc3(sr1, sr2, srm=None):
    return get_fastq_record_triplet(
        read_id=str(ID),
        sr1=sr1,
        sr2=sr2,
        srm=srm,
        barcode1="TGGGAGCC",
        barcode2="ATAGAGGC",
    )

snp_1_a_id = 1
snp_1_b_id = 2
snp_2_a_id = 3
snp_relative_position_1 = 62
snp_relative_position_2 = 112
magicalpcr1library_id = 1
magicalpcr1barcodedcontent_id = 1
magicalpcr1barcodedcontent_a_id = 2
pu_snp_example_1 = 5
pu_snp_example_2 = 6
utm_snp_example_1 = 7
pu_snp_example_3 = 8
pu_snp_example_4 = 31584


def snp_genotype(base):  # Just to give the int some context
    return base


def snp_genotype_ref(base):  # Just to give the int some context
    return base


def snp_genotype_alt(base):  # Just to give the int some context
    return base

READS_DICT_FULL_SNP = {
    magicalpcr1library_id: {
        magicalpcr1barcodedcontent_id: {
            pu_snp_example_1: {
                frozenset(((snp_1_a_id, snp_genotype('nan')), (snp_1_b_id, snp_genotype('C')),)): [
                    bc1(
                        sr1="TACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCATGGCACTGTACTCTTCCTGTCCAGCTGTATCCAGTATGTCCAACAAACAGGTTTCACCATCTATAACCACTTGTTTTCTGTAAGAATCCTGGGGGTGTGGA",
                        sr2="TCCACACCCCCAGGATTCTTACAGAAAACAAGTGGTTATAGATGGTGAAACCTGTTTGTTGGACATACTGGATACAGCTGGACGAGAAGAGTACAGTGCCATGAGAGACCAATACATGAGGACAGGCGAAGGCTTCCTCTGTGTA",
                    ),
                    bc1(
                        sr1="TACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCATGGCACTGTACTCTTCTTGTCCAGCTGTATCCAGTATGTCCAACAAACAGGTTTCACCATCTATAACCACTTGTTTTCTGTAAGAATCCTGGGGGTGTGGA",
                        sr2="TCCACACCCCCAGGATTCTTACAGAAAACAAGTGGTTATAGATGGTGAAACCTGTTTGTTGGACATACTGGATACAGCTGGACAAGAAGAGTACAGTGCCATGAGAGACCAATACATGAGGACAGGCGAAGGCTTCCTCTGTGTA",
                    ),


                ]
            },
            pu_snp_example_2: {
                frozenset(((snp_2_a_id, snp_genotype('C')),)): [
                    bc1(
                        sr1="AGATGTGGAACATGGCATTTTTGCTTCCATATTAATTTATACGGCCACAAAAAACTGCATGGAAGACTTAGAAATATAGTCTAGCTTTAGGCACAAAGGAGGTGTCAACAAGTTTTGGCTAGCTAGCTGGGAGTCCCCGCCAAGTCATGTGGAATATTCTTGTAATGTCATCAATACTCCAAGTTCTCCAAATTAAGATTCCTTTTCATCTTAATCTTCTCACTGTTAGGCAGGTTC",
                        sr2="GAACCTGCCTAACAGTGAGAAGATTAAGATGAAAAGGAATCTTAATTTGGAGAACTTGGAGTATTGATGACATTACAAGAATATTCCACATGACTTGGCGGGGACTCCCAGCTAGCTAGCCAAAACTTGTTGACACCTCCTTTGTGCCTAAAGCTAGACTATATTTCTAAGTCTTCCATGCAGTTTTTTGTGGCCGTATAAATTAATATGGAAGCAAAAATGCCATGTTCCACATCT",
                    ),
                    bc1(
                        sr1="AGATGTGGAACATGGCATTTTTGCTTCCATATTAATTTATACGGCCACAAAAAACTGCATGGAAGACTTAGAAATATAGTCTAGCTTTAGGCACAAAGGAGGTGTCAACAACTTTTGGCTAGCTAGCTGGGAGTCCCCGCCAAGTCATGTGGAATATTCTTGTAATGTCATCAATACTCCAAGTTCTCCAAATTAAGATTCCTTTTCATCTTAATCTTCTCACTGTTAGGCAGGTTC",
                        sr2="GAACCTGCCTAACAGTGAGAAGATTAAGATGAAAAGGAATCTTAATTTGGAGAACTTGGAGTATTGATGACATTACAAGAATATTCCACATGACTTGGCGGGGACTCCCAGCTAGCTAGCCAAAAGTTGTTGACACCTCCTTTGTGCCTAAAGCTAGACTATATTTCTAAGTCTTCCATGCAGTTTTTTGTGGCCGTATAAATTAATATGGAAGCAAAAATGCCATGTTCCACATCT",
                    ),
                ],
            },

        },
        magicalpcr1barcodedcontent_a_id: {
            pu_snp_example_1: {
                frozenset(((snp_1_a_id, snp_genotype('nan')), (snp_1_b_id, snp_genotype('C')),)): [
                    bc1(
                        sr1="TACACAGAGGAAGCCTTCGCCTGTCCTCATGTATTGGTCTCTCATGGCACTGTACTCTTCCTGTCCAGCTGTATCCAGTATGTCCAACAAACAGGTTTCACCATCTATAACCACTTGTTTTCTGTAAGAATCCTGGGGGTGTGGA",
                        sr2="TCCACACCCCCAGGATTCTTACAGAAAACAAGTGGTTATAGATGGTGAAACCTGTTTGTTGGACATACTGGATACAGCTGGACAAGAAGAGTACAGTGCCATGAGAGACCAATACATGAGGACAGGCGAAGGCTTCCTCTGTGTA",
                    ),
                ]
            },
            pu_snp_example_2: {
                frozenset(((snp_2_a_id, snp_genotype('C')),)): [
                    bc1(
                        sr1="AGATGTGGAACATGGCATTTTTGCTTCCATATTAATTTATACGGCCACAAAAAACTGCATGGAAGACTTAGAAATATAGTCTAGCTTTAGGCACAAAGGAGGTGTCAACAACTTTTGGCTAGCTAGCTGGGAGTCCCCGCCAAGTCATGTGGAATATTCTTGTAATGTCATCAATACTCCAAGTTCTCCAAATTAAGATTCCTTTTCATCTTAATCTTCTCACTGTTAGGCAGGTTC",
                        sr2="GAACCTGCCTAACAGTGAGAAGATTAAGATGAAAAGGAATCTTAATTTGGAGAACTTGGAGTATTGATGACATTACAAGAATATTCCACATGACTTGGCGGGGACTCCCAGCTAGCTAGCCAAAAGTTGTTGACACCTCCTTTGTGCCTAAAGCTAGACTATATTTCTAAGTCTTCCATGCAGTTTTTTGTGGCCGTATAAATTAATATGGAAGCAAAAATGCCATGTTCCACATCT",
                    ),
                ],
            },

            pu_snp_example_3: {
                frozenset(((None, snp_genotype('nan')),)): [
                    bc1(
                        sr1="TAGGCAGCACGGAGCAGAGGAAGTTGGGGCTGTCGGTGCGCACCAGCTCGCCCGGGTGGTCGGCCAGCACCTCCACCATGCTGCGGTCGCCGCTCCTCAGCTTGCCGGCCAGGGCAGCGCCGGCGTCCGGGGCGCCCAGCGGCAACGCCTCGCTCATCTTGCCTGGGCTCAGCGCGGTGGAAGGCGGCGTGAAGCGGCGGCTCGTGCTGGCATCTACGGGGATACGCATCACAACAAGCCGATTGAGTTAGGACCCTGCAAA",
                        sr2="TTTGCAGGGTCCTAACTCAATCGGCTTGTTGTGATGCGTATCCCCGTAGATGCCAGCACGAGCCGCCGCTTCACGCCGCCTTCCACCGCGCTGAGCCCAGGCAAGATGAGCGAGGCGTTGCCGCTGGGCGCCCCGGACGCCGGCGCTGCCCTGGCCGGCAAGCTGAGGAGCGGCGACCGCAGCATGGTGGAGGTGCTGGCCGACCACCCGGGCGAGCTGGTGCGCACCGACAGCCCCAACTTCCTCTGCTCCGTGCTGCCTA",
                    ),
                ]
            },
            pu_snp_example_4: {
                frozenset(((None, snp_genotype('nan')),)): [
                    bc1(
                        sr1="AATTCAACTAGAGGGCAGCCTTGTGGATGGCCCCGAAGCAAGCCTGATGGAACAGGATAGAACCAACCATGTTGAGGGCAACAGACTAAGTCCATTCCTGATACCATCACCTCCCATTTGCCAGACAGAACCTCTGGCTACAAAGCTCCAGAATGGAAGCCCACTGCCTGAGAGAGCTCATCCAGAAGTAAATGGAGACACCAAGTGGCA",
                        sr2="TGCCACTTGGTGTCTCCATTTACTTCTGGATGAGCTCTCTCAGGCAGTGGGCTTCCATTCTGGAGCTTTGTAGCCAGAGGTTCTGTCTGGCAAATGGGAGGTGATGGTATCAGGAATGGACTTAGTCTGTTGCCCTCAACATGGTTGGTTCTATCCTGTTCCATCAGGCTTGCTTCGGGGCCATCCACAAGGCTGCCCTCTAGTTGAATT",
                    ),
                ]
            },
            utm_snp_example_1: {
                frozenset(((snp_1_a_id, snp_genotype('nan')), (snp_1_b_id, snp_genotype('C')),)): [
                    bc1(
                        sr1="NNNAATTCAACTAGAGGGCAGCCTTGTGGATGGCCCCGAAGCAAGCCTGATGGAACAGGATAGAACCAACCATGTTGAGGGCAACAGACTAAGTCCATTCCTGATACCATCACCTCCCATTTGCCAGACAGAACCTCTGGCTACAAAGCTCCAGAATGGAAGCCCACTGCCTGAGAGAGCTCATCCAGAAGTAAATGGAGACACCAAGTGGCANNN",
                        sr2="NNNTGCCACTTGGTGTCTCCATTTACTTCTGGATGAGCTCTCTCAGGCAGTGGGCTTCCATTCTGGAGCTTTGTAGCCAGAGGTTCTGTCTGGCAAATGGGAGGTGATGGTATCAGGAATGGACTTAGTCTGTTGCCCTCAACATGGTTGGTTCTATCCTGTTCCATCAGGCTTGCTTCGGGGCCATCCACAAGGCTGCCCTCTAGTTGAATTNNN",
                    ),
                ]
            },
        },
    },
}
