version: "3"
    
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clineage_prod
      MYSQL_USER: dcsoft
      MYSQL_PASSWORD: 164d8ae81bd7e38a163ea2e144114b25

  clineage-web:
    depends_on:
      - db
    image: clineage:0.0.3
    restart: always
    volumes:
      - ./resources/local_settings.py:/clineage/clineage/local_settings.py
      - ./resources/init_once_clineage_web.sh:/init_once.sh
      - ./resources/entrypoint_clineage_web.sh:/entrypoint.sh
      - data_store:/data_store
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: clineage_prod
      MYSQL_USER: dcsoft
      MYSQL_PASSWORD: 164d8ae81bd7e38a163ea2e144114b25

  task-scheduler:
    image: clineage:0.0.3
    volumes:
      - ./resources/entrypoint_task_scheduler.sh:/entrypoint.sh
    ports:
      - 8787:8787
    restart: always

  clineage-worker:
    depends_on:
      - clineage-web
      - task-scheduler
    image: clineage:0.0.3
    restart: always
    volumes:
      - ./resources/local_settings.py:/clineage/clineage/local_settings.py
      - data_store:/data_store
      - ./resources/entrypoint_clineage_worker.sh:/entrypoint.sh
      #- ./resources/entrypoint_debug.sh:/entrypoint.sh
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: clineage_prod
      MYSQL_USER: dcsoft
      MYSQL_PASSWORD: 164d8ae81bd7e38a163ea2e144114b25

  jupyter:
    depends_on:
      - db
      - clineage-web
    image: clineage:0.0.3
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: clineage_prod
      MYSQL_USER: dcsoft
      MYSQL_PASSWORD: 164d8ae81bd7e38a163ea2e144114b25
    volumes:
      - ./resources/local_settings.py:/clineage/clineage/local_settings.py
      - ./resources/entrypoint_jupyter1.sh:/entrypoint.sh
      - /ukr/local/lineage/notebooks:/clineage/notebooks2
      - data_store:/data_store
    ports:
      - 8888:8888
    restart: always

volumes:
  db_data: {}
  data_store: {}
