# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import targeted_enrichment.reagents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('synthesis', '0001_initial'),
        ('amplicons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM6PadlockTERBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_validation', models.NullBooleanField()),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('old_adam_te_pk', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCR1PrimerPairTERBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_validation', models.NullBooleanField()),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('old_adam_te_pk', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(targeted_enrichment.reagents.models.TwoPrimersStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetedNoTailPrimerPairTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_validation', models.NullBooleanField()),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('old_adam_te_pk', models.PositiveIntegerField(null=True)),
                ('amplicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.PlainTargetedAmplicon')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.TargetedNoTailPlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.TargetedNoTailMinusPrimer')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.TargetEnrichment')),
            ],
            options={
                'abstract': False,
            },
            bases=(targeted_enrichment.reagents.models.TwoPrimersStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetEnrichmentFailureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OM6PadlockTER',
            fields=[
                ('om6padlockterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.OM6PadlockTERBase')),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.OM6Padlock')),
            ],
            options={
                'abstract': False,
            },
            bases=('reagents.om6padlockterbase',),
        ),
        migrations.CreateModel(
            name='OM6PadlockTERDeprecated',
            fields=[
                ('om6padlockterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.OM6PadlockTERBase')),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.OM6PadlockDeprecated')),
            ],
            options={
                'abstract': False,
            },
            bases=('reagents.om6padlockterbase',),
        ),
        migrations.CreateModel(
            name='PCR1PrimerPairTER',
            fields=[
                ('pcr1primerpairterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.PCR1PrimerPairTERBase')),
                ('amplicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.PlainTargetedAmplicon')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1PlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1MinusPrimer')),
            ],
            options={
                'abstract': False,
            },
            bases=('reagents.pcr1primerpairterbase',),
        ),
        migrations.CreateModel(
            name='PCR1PrimerPairTERDeprecated',
            fields=[
                ('pcr1primerpairterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.PCR1PrimerPairTERBase')),
                ('amplicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.PlainTargetedAmplicon')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1PlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1MinusPrimer')),
            ],
            options={
                'abstract': False,
            },
            bases=('reagents.pcr1primerpairterbase',),
        ),
        migrations.CreateModel(
            name='PCR1WithCompanyTagPrimerPairTER',
            fields=[
                ('pcr1primerpairterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.PCR1PrimerPairTERBase')),
                ('amplicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.TargetedAmpliconWithCompanyTag')),
                ('left_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1WithCompanyTagPlusPrimer')),
                ('right_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthesis.PCR1WithCompanyTagMinusPrimer')),
            ],
            options={
                'abstract': False,
            },
            bases=('reagents.pcr1primerpairterbase',),
        ),
        migrations.AddField(
            model_name='targetednotailprimerpairter',
            name='validation_failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reagents.TargetEnrichmentFailureType'),
        ),
        migrations.AddField(
            model_name='pcr1primerpairterbase',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.TargetEnrichment'),
        ),
        migrations.AddField(
            model_name='pcr1primerpairterbase',
            name='validation_failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reagents.TargetEnrichmentFailureType'),
        ),
        migrations.AddField(
            model_name='om6padlockterbase',
            name='amplicon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplicons.UMITargetedAmplicon'),
        ),
        migrations.AddField(
            model_name='om6padlockterbase',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.TargetEnrichment'),
        ),
        migrations.AddField(
            model_name='om6padlockterbase',
            name='validation_failure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reagents.TargetEnrichmentFailureType'),
        ),
    ]
